# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rebecca/common/net/network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "rebecca/common/net/network.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n rebecca/common/net/network.proto\x12\x12rebecca.common.net";\n\x0bNetworkList\x12,\n\x07network\x18\x01 \x03(\x0e\x32\x1b.rebecca.common.net.Network*8\n\x07Network\x12\x0b\n\x07Unknown\x10\x00\x12\x0e\n\x06RawTCP\x10\x01\x1a\x02\x08\x01\x12\x07\n\x03TCP\x10\x02\x12\x07\n\x03UDP\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rebecca.common.net.network_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NETWORK"].values_by_name["RawTCP"]._loaded_options = None
    _globals["_NETWORK"].values_by_name["RawTCP"]._serialized_options = b"\010\001"
    _globals["_NETWORK"]._serialized_start = 117
    _globals["_NETWORK"]._serialized_end = 173
    _globals["_NETWORKLIST"]._serialized_start = 56
    _globals["_NETWORKLIST"]._serialized_end = 115
# @@protoc_insertion_point(module_scope)
